name: Badge Magic Push CI

on:
  push:
    branches: ["flutter_app"]

env:
  ANDROID_EMULATOR_API: 34
  ANDROID_EMULATOR_ARCH: x86_64

jobs:
  common:
    name: Common Build
    runs-on: ubuntu-latest
    outputs:
      VERSION_NAME: ${{ steps.flutter-version.outputs.VERSION_NAME }}
      VERSION_CODE: ${{ steps.flutter-version.outputs.VERSION_CODE }}
    steps:
      - uses: actions/checkout@v4
      - name: Common Workflow
        uses: ./.github/actions/common
      - name: Hydrate and Update Version
        id: flutter-version
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Increment version number and code
          git clone --branch=version https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }} version
          cd version
          IFS='.' read -r major minor patch < versionName.txt
          echo "VERSION_NAME=$major.$minor.$patch" >> $GITHUB_OUTPUT
          echo "$major.$minor.$((patch+1))" > versionName.txt

          read -r version_code < versionCode.txt
          echo "VERSION_CODE=$((version_code + 1))" > versionCode.txt

          # Push version updates to version branch
          git checkout --orphan temporary
          git add --all .
          git commit -am "[Auto] Update versions"
          git branch -D version
          git branch -m version
          git push --force origin version

  android:
    name: Android Flutter Build
    needs: common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pre Checks
        run: |
          bash scripts/check-screenshots.sh

      - name: Prepare Build Keys
        if: ${{ github.repository == 'fossasia/badgemagic-android' }}
        env:
          ENCRYPTED_F10B5E0E5262_IV: ${{ secrets.ENCRYPTED_F10B5E0E5262_IV }}
          ENCRYPTED_F10B5E0E5262_KEY: ${{ secrets.ENCRYPTED_F10B5E0E5262_KEY }}
        run: |
          bash scripts/prep-key.sh

      - name: Android Workflow
        uses: ./.github/actions/android
        with:
          STORE_PASS: ${{ secrets.STORE_PASS }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
          VERSION_NAME: ${{needs.common.outputs.VERSION_NAME}}
          VERSION_CODE: ${{needs.common.outputs.VERSION_CODE}}

      - name: Upload APK to apk Branch
        if: ${{ github.repository == 'fossasia/badgemagic-android' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git clone --branch=apk https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }} apk
          cd apk

          # Remove previous APK files
          rm -rf badge-magic-*

          # Copy new APK and AAB files
          cp ../build/app/outputs/flutter-apk/app-release.apk ./badge-magic-${{ needs.common.outputs.VERSION_NAME }}.apk
          cp ../build/app/outputs/bundle/app-release.aab ./badge-magic-${{ needs.common.outputs.VERSION_NAME }}.aab

          # Push updated files to apk branch
          git add --all .
          git commit -am "[Auto] Updated APK/AABs for version ${{ needs.common.outputs.VERSION_NAME }}"
          git push --force origin apk

  delete-apk-branch:
    name: Delete APK Branch
    runs-on: ubuntu-latest
    needs: android
    if: always() # Ensures deletion even if the build fails
    steps:
      - name: Delete APK Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --delete apk
